---
version: "3"

services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    user:
    command: [ "--save", "1", "1" ]
  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis-db
    image: flask-app:1.0
    container_name: flask-app
    ports:
      - "5000:5000"
...
