---
version: "3"

services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: [ "--save", "1", "1" ]
  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: flask-app:1.0
    container_name: flask-app
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/now" ]
      interval: 3s
      timeout: 2s
      retries: 10

  flask-test:
    image: flask-app:1.0
    container_name: flask-test
    depends_on:
      flask-app:
        condition: service_healthy
    entrypoint: [ "pytest" ]
...
